name: payon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.1
  skeletonizer: ^2.1.3
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  iconsax_flutter: ^1.0.1
  intl: ^0.20.2
  package_info_plus: ^9.0.1
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5
  smooth_page_indicator: ^2.0.1
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  go_router: ^17.2.2
  get_it: ^9.2.1
  image_picker: ^1.1.2
  country_flags: ^4.1.2
  dio: ^5.9.2
  retrofit: ^4.9.2
  flutter_hooks: ^0.21.3+1
  formz: ^0.8.0
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.0.0
  argon2: ^1.0.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.14.0
  freezed: ^3.2.5
  json_serializable: 6.13.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  intl_utils: ^2.8.14
  retrofit_generator: ^10.2.3
  pretty_dio_logger: ^1.4.0
  go_router_builder: ^4.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/svgs/

  fonts:
  - family: Rubik
    fonts:
    - asset: assets/fonts/ar/Rubik/static/Rubik-Regular.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-Italic.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-Light.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-LightItalic.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-Medium.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-MediumItalic.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-SemiBold.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-SemiBoldItalic.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-Bold.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-BoldItalic.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-ExtraBold.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-ExtraBoldItalic.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-Black.ttf
    - asset: assets/fonts/ar/Rubik/static/Rubik-BlackItalic.ttf

  - family: KaiseiTokumin
    fonts:
    - asset: assets/fonts/ja/Kaisei_Tokumin/KaiseiTokumin-Regular.ttf
      weight: 400
    - asset: assets/fonts/ja/Kaisei_Tokumin/KaiseiTokumin-Bold.ttf
      weight: 700
    - asset: assets/fonts/ja/Kaisei_Tokumin/KaiseiTokumin-ExtraBold.ttf
      weight: 800
